### ISSUE TITLE
Rockchip HW acceleration not working on Orange Pi 5 plus 16GB

### ISSUE THREAD

**Issue by abratchik** [nyanmisaka/ffmpeg-rockchip#95]
Hello, 

I'm experimenting with the Orange PI5 Plus box and the frigate version with rknn but it doesnt seem to work on my setup at all. The inference seems to be very poor and also Capture FPS is close to zero. Hence all the detects are skipped:

<img width="602" alt="Screenshot 2024-08-06 at 5 36 16 PM" src="https://github.com/user-attachments/assets/f2823b32-f482-426b-830e-83f80db0259c">

Please kindly help me to understand what I'm missing. 

Here is my setup:

**OS/Kernel:** Linux orangepi5plus 6.1.43-rockchip-rk3588 #1.0.8 SMP Sat Feb  3 00:04:38 CST 2024 aarch64 aarch64 aarch64 GNU/Linux

**docker-compose.yml**

```
services:
    mqtt:
      container_name: mqtt
      image: eclipse-mosquitto:2
      restart: unless-stopped
      volumes:
        - /home/orangepi/config/mqtt:/mosquitto/config
      ports:
        - "1833:1833"
      networks:
        - br0
    frigate:
      container_name: frigate
      image: marca711/frigate:latest-rk 
#      image: ghcr.io/blakeblackshear/frigate:stable-rk
      privileged: true 
      restart: unless-stopped
      group_add:
        - "106" # render
        - "44"  # video
        - "46"  # plugdev
      security_opt:
        - apparmor=unconfined
      devices:
        - /dev/dri:/dev/dri
        - /dev/dri/renderD128:/dev/dri/renderD128
        - /dev/dma_heap:/dev/dma_heap
        - /dev/rga:/dev/rga
        - /dev/mpp_service:/dev/mpp_service
      volumes:
        - /home/orangepi/config/frigate/patches/usr/lib/btbn-ffmpeg/bin:/usr/lib/btbn-ffmpeg/bin # patch ffmpeg
        - /home/orangepi/config/frigate/patches/opt/frigate/frigate/ffmpeg_presets.py:/opt/frigate/frigate/ffmpeg_presets.py
        - /home/orangepi/config/frigate/patches/usr/local/go2rtc/create_config.py:/usr/local/go2rtc/create_config.py
        - /dev/bus/usb:/dev/bus/usb
        - /etc/localtime:/etc/localtime:ro
        - /home/orangepi/config/frigate/config.yml:/config/config.yml:rw
        - /home/orangepi/config/frigate/storage:/media/frigate:rw
        - type: tmpfs # 1GB of memory, reduces SSD/SD Card wear
          target: /tmp/cache
          tmpfs:
            size: 1000000000
      ports:
        - "5000:5000"
        - "1935:1935"
        - "8554:8554" # RTSP feeds
        - "8555:8555/tcp" # WebRTC over tcp
        - "8555:8555/udp" # WebRTC over udp
      networks:
        - br0
      device_cgroup_rules:
        - "c 189:* rmw"
      env_file:
        - ./.env.client

networks:
  br0:
    name: br0
```

**config.yml**

```
mqtt:
  enabled: true
  topic_prefix: frigate
  client_id: frigate
  host: mqtt
  user: '{FRIGATE_MQTT_USR}'
  password: '{FRIGATE_MQTT_PWD}'

logger:
  default: info

detectors:
  rknn:
    type: rknn
    core_mask: 0b111
model:
  path: default-yolov8n
  width: 320
  height: 320
  input_tensor: nhwc
  input_pixel_format: bgr

record:
  enabled: true
  retain:
    days: 7
    mode: motion
  events:
    retain:
      default: 7
      mode: motion

snapshots:
  enabled: true
  retain:
    default: 7

cameras:
  cam7:
    enabled: true
    ffmpeg:
      input_args: preset-rtsp-restream
      hwaccel_args: preset-rk-h265
      inputs:
      - path: rtsp://{FRIGATE_RTSP_USR}:{FRIGATE_RTSP_PWD2}@192.168.0.12:554/channel=1_stream=1&amp;onvif=0.sdp?real_st
        roles:
        - detect
    detect:
      enabled: true
      width: 800
      height: 488
      fps: 5
    objects:
      track:
        - person
```

The frigate starts normally with no obvious issues but then I see the log full of messages like:

```
2024-08-06 17:31:22.543948520  E RKNN: [17:31:22.543] failed to submit!, op id: 7, op name: Add:/model.2/m.0/Add, flags: 0x5, task start: 1390, task number: 6, run task counter: 0, int status: 0, please try updating to the latest version of the toolkit2 and runtime from: https://console.zbox.filez.com/l/I00fc3 (PWD: rknn)
```

is there an image where this is fixed already? Or I need to update the host?
